name: CI
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            -   uses: actions/checkout@v4
            -   name: Build demo
                run: |
                    echo "Enter demo folder"
                    cd demo
                    
                    echo "npm ci"
                    npm ci
                    
                    echo "check node_modules"
                    ls -lah node_modules
                    
                    echo "npm run build"
                    npm run build
                    
                    echo "move dist files"
                    cp -a dist/. ../public/
